"""Add tags field to Event model

Revision ID: 158f65ae60eb
Revises: ed0ca46be275
Create Date: 2024-12-08 16:20:36.813649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158f65ae60eb'
down_revision = 'ed0ca46be275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
